use Mix.Config

config :clash_of_clans_slackbot, token: "xoxb-41598186912-R39ToPMPdsKqCJB84pNqTgsQ"
config :clash_of_clans_slackbot, database: "dev.sqlite3"
config :clash_of_clans_slackbot, clashapi_token: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6IjcyODVhMDg3LTBkYjMtNDQ0Zi1iZjI0LTFiYzY4ZjFhYzkzZCIsImlhdCI6MTQ1NDg3NTM4Miwic3ViIjoiZGV2ZWxvcGVyLzFmMjUyZGNkLTc4OTAtODg5Zi04MjFhLThkY2MxYjVkYTk0NCIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjYyLjQ1LjEyMi4yMzQiXSwidHlwZSI6ImNsaWVudCJ9XX0.aRIayqnFhU4HoWctm5Izhg37tZ1AxYDnchP4si59CP4_on4OBYclLK500AyjyN-I-DhYuhcViWh4u0fA_MOZvA"
config :clash_of_clans_slackbot, post_channel: "bottesting"
config :clash_of_clans_slackbot, clantag: "#C8000C0"
config :clash_of_clans_slackbot, war_url_filename: "data/dev_war_url.bk"
